config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :roles
  put "csfs/update_selected_csf", to: "csfs#update_selected_csf"
  resources :csfs
  resources :values
  put "visions/update_selected_vision", to: "visions#update_selected_vision"
  resources :visions, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :activities do
    collection do
      put :checked
    end
  end
  resources :goals

  get "spheres/update_sphere_completion", to: "spheres#update_sphere_completion"
  get "sphereobjectives", to: "spheres#sphereobjectives"
  resources :spheres

  get "editobjective", to: "objectives#editobjective"
  resources :objectives

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
    delete 'users/destroy_another_user', :to => 'users/registrations#destroy_another_user'
  end
  resources :swotparts

  put "missions/update_selected_mission", to: "missions#update_selected_mission"
  resources :missions, only: [:index, :new, :create, :destroy, :edit, :update]

  get "plans/import_page", to: "plans#import_page"
  get "plans/export", to: "plans#export"
  get "plans/pdf", to: "plans#pdf"
  put "plans/update_selected_plan", to: "plans#update_selected_plan"
  get "swot", to:"plans#swot"
  get "myplan", to: "plans#myplan"
  get "plans/swotedit", to: "plans#swotedit"
  get "inicio", to:"plans#inicio"
  resources :plans do
    collection { post :import }
  end

  get "home/contribution", to: "home#contribution"
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @contact = Contact.new
    @disable_nav = true
    @disable_footer = true
  end

  def contribution
  end
end

app/views/home/_headertemplate.html.erb
<!-- start header -->
<header>
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12">
        <p><i class="fa fa-phone"></i><span> Phone</span>010-020-0340</p>
      </div>
      <div class="col-md-3 col-sm-4 col-xs-12">
        <p><i class="fa fa-envelope-o"></i><span> Email</span><a href="#">awesome@company.com</a></p>
      </div>
      <div class="col-md-5 col-sm-4 col-xs-12">
        <ul class="social-icon">
          <li><span>Meet us on</span></li>
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-apple"></a></li>
        </ul>
      </div>
    </div>
  </div>
</header>
<!-- end header -->

app/views/home/_navbarlanding.html.erb
<!-- start navigation -->
<nav class="navbar navbar-default templatemo-nav" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
        <span class="icon icon-bar"></span>
      </button>
      <%= link_to root_path, method: "get" do %>
        <%= image_tag("ltr2.svg", alt:"logo img 1", class: "image-responsive resize-navbrand p-t-10") %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- href to #top, about, team, service, portifolio, contact -->
        <li><a href="#top">HOME</a></li>
        <li><a href="#about">SOBRE</a></li>

        <li><%= link_to "MEU PLANEJAMENTO", myplan_path, method: "get" %></li>
        <% if current_user %>
          <li><%= link_to " Olá #{current_user.name}", edit_user_registration_path, method: "get", class:"lnr lnr-user" %></li>
          <li><%= link_to "Finalizar Demonstração", user_registration_path, data: {confirm: "Tem certeza que deseja sair? Por ser uma versão de demonstração, seu usuário será apagado."}, method: :delete %></li>
        <% else %>
          <li><%= link_to "ENTRAR", new_user_session_path, method: "get" %></li>
          <li><%= link_to "CADASTRAR", new_user_registration_path, method: "get" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- end navigation -->

app/views/home/_team.html.erb
<!-- start team -->
<section id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><span>AWESOME</span> TEAM</h2>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.3s">
        <div class="team-wrapper">
          <%= image_tag("team-img2.jpg", alt: "team img 1", class: "img-responsive") %>
          <div class="team-des">
            <h4>TRACY</h4>
            <span>Designer</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.6s">
        <div class="team-wrapper">
          <%= image_tag("team-img2.jpg", alt: "team img 2", class: "img-responsive") %>
          <div class="team-des">
            <h4>MARY</h4>
            <span>Developer</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.3s">
        <div class="team-wrapper">
          <%= image_tag("team-img2.jpg", alt: "team img 3", class: "img-responsive") %>
          <div class="team-des">
            <h4>JULIA</h4>
            <span>Director</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="1.6s">
        <div class="team-wrapper">
          <%= image_tag("team-img2.jpg", alt: "team img 4", class: "img-responsive") %>
          <div class="team-des">
            <h4>LINDA</h4>
            <span>Manager</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elitquisque tempus ac eget diam et laoreet phasellus ut nisi id leo molest.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end team -->

app/views/home/contribution.html.erb
<div class="container">
  <h3 class="p-t-50 p-b-10">Contribua para o projeto Life to Remind</h3>

  <hr/>
  <h4>Contribua como Desenvolvedor</h4>
  <br/>

  <div class="container">
    <a href="https://gitlab.com/edu_qg/ltr" class="color-dark">Link do Repositório</a>
    <br/>
    <br/>

    <h5>Principais desenvolvedores </h5>
    <br/>
    <div class="container">
      <h5>1) @_____________ </h5>
      <h5>2) @_____________ </h5>
      <h5>3) @_____________ </h5>
    </div>
  </div>

  <hr/>

  <h4>Faça uma doação para o projeto</h4>
  <br/>
  <div class="container">
    <h5></h5>
  </div>
  <hr/>

  <h4>Seja um patrocinador</h4>
  <br/>
  <div class="container">
    <h5>Ainda não temos um patrocinador, entre em contato para saber mais.</h5>
  </div>
</div>

app/views/home/index.html.erb
<body id="top">

<!-- start preloader -->
<div class="preloader">
  <div class="sk-spinner sk-spinner-wave">
    <div class="sk-rect1"></div>
    <div class="sk-rect2"></div>
    <div class="sk-rect3"></div>
    <div class="sk-rect4"></div>
    <div class="sk-rect5"></div>
  </div>
</div>
<!-- end preloader -->

<!-- %= render "headertemplate" % -->

<%= render "navbarlanding" %>

<!-- start home -->
<section id="home">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <h1 class="wow fadeIn color-white" data-wow-offset="50" data-wow-delay="0.9s">
          <span>Life to Remind</span><span class="home-version">Demonstração</span></h1>
        <div class="element">
          <div class="sub-element">Life To Remind</div>
          <div class="sub-element">Planeje sua vida</div>
          <div class="sub-element">Alcance objetivos</div>
        </div>
        <!-- a data-scroll href="#about" class="btn btn-default wow fadeInUp" data-wow-offset="50" data-wow-delay="0.6s">COMEÇAR</a -->
        <%= link_to "COMEÇAR", new_plan_path, class: "btn btn-default wow fadeInUp", method: "get" %>
      </div>
    </div>
  </div>
</section>
<!-- end home -->

<!-- start about -->
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">O que é o <span>Life to Remind</span></h2>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="media">
          <div class="media-heading-wrapper">
            <div class="media-object pull-left">
              <i class="fa fa-mobile"></i>
            </div>
            <h3 class="media-heading">LIFE TO REMIND</h3>
          </div>
          <div class="media-body">
            <p>Sua vida é muito importante. Faça o planejamento dela no Life to Remind, acompanhe seus objetivos de vida
              pessoais, financeiros e profissionais ou outro âmbito de sua escolha.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInUp" data-wow-offset="50" data-wow-delay="0.9s">
        <div class="media">
          <div class="media-heading-wrapper">
            <div class="media-object pull-left">
              <i class="fa fa-comment-o"></i>
            </div>
            <h3 class="media-heading">UM PLANO INDIVIDUAL</h3>
          </div>
          <div class="media-body">
            <p>Conheça mais a si mesmo. Entenda melhor quem é você, no que é bom, forças, fraquezas, oportunidades e
              ameaças ao seu redor. Além disso, descobra seu propósito de vida, missão, valores dentre outras
              características individuais.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInRight" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="media">
          <div class="media-heading-wrapper">
            <div class="media-object pull-left">
              <i class="fa fa-html5"></i>
            </div>
            <h3 class="media-heading">REDIRECIONE SEU CAMINHO</h3>
          </div>
          <div class="media-body">
            <p>O Life to Remind te ajuda conhecer e seguir seu caminho. Objetivos também podem mudar no decorrer da
              vida, por que não acompanha-los?</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end about -->

<!-- % render "team" % -->

<!-- start service -->
<section id="service">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">O que o <span>LTR</span> possui</h2>
      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-layers color-white"></i>
        <h4>Planos</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">
        <i class="lnr lnr-file-add color-white"></i>
        <h4>Análise Ambitental - Matriz SWOT</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-pushpin color-white"></i>
        <h4>Missão</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-layers color-white"></i>
        <h4>Valores</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">
        <i class="lnr lnr-file-add color-white"></i>
        <h4>Papéis</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-pushpin color-white"></i>
        <h4>Fatores Críticos de Sucesso</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-layers color-white"></i>
        <h4>Objetivos Estratégicos Pessoais</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.9s">
        <i class="lnr lnr-file-add color-white"></i>
        <h4>Metas</h4>

      </div>
      <div class="col-md-4 active wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <i class="lnr lnr-pushpin color-white"></i>
        <h4>Atividades</h4>

      </div>
    </div>
  </div>
</section>
<!-- end servie -->

<!-- start portfolio -->
<section id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s">MEU <span>PLANEJAMENTO</span></h2>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("plan1.png", alt: "portfolio img 1", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Meu plano</h4>
            <%= link_to "Detalhes", myplan_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("mission1.png", alt: "portfolio img 2", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Minha missão</h4>
            <%= link_to "Detalhes", new_mission_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("sphere1.png", alt: "portfolio img 3", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Âmbitos e Objetivos</h4>
            <%= link_to "Detalhes", new_objective_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("meta1.png", alt: "portfolio img 4", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Metas e Atividades</h4>
            <%= link_to "Detalhes", new_objective_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("status1.png", alt: "portfolio img 5", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Status</h4>
            <%= link_to "Detalhes", inicio_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-offset="50" data-wow-delay="0.6s">
        <div class="portfolio-thumb">
          <%= image_tag("status2.png", alt: "portfolio img 6", class: "img-responsive border-ltr") %>
          <div class="portfolio-overlay">
            <h4>Análise Ambiental</h4>
            <%= link_to "Detalhes", plans_swotedit_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end portfolio -->

<%= render template: "contacts/new" %>

<!-- start copyright -->
<footer id="copyright" class="background-blue-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center p-b-10">
        <p class="wow bounceIn color-white" data-wow-offset="50" data-wow-delay="0.3s">
          Copyright &copy; 2019 Life to Remind</p>
      </div>
    </div>
  </div>
</footer>
<!-- end copyright -->

</body>