config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :roles
  put "csfs/update_selected_csf", to: "csfs#update_selected_csf"
  resources :csfs
  resources :values
  put "visions/update_selected_vision", to: "visions#update_selected_vision"
  resources :visions, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :activities do
    collection do
      put :checked
    end
  end
  resources :goals

  get "spheres/update_sphere_completion", to: "spheres#update_sphere_completion"
  get "sphereobjectives", to: "spheres#sphereobjectives"
  resources :spheres

  get "editobjective", to: "objectives#editobjective"
  resources :objectives

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
    delete 'users/destroy_another_user', :to => 'users/registrations#destroy_another_user'
  end
  resources :swotparts

  put "missions/update_selected_mission", to: "missions#update_selected_mission"
  resources :missions, only: [:index, :new, :create, :destroy, :edit, :update]

  get "plans/import_page", to: "plans#import_page"
  get "plans/export", to: "plans#export"
  get "plans/pdf", to: "plans#pdf"
  put "plans/update_selected_plan", to: "plans#update_selected_plan"
  get "swot", to:"plans#swot"
  get "myplan", to: "plans#myplan"
  get "plans/swotedit", to: "plans#swotedit"
  get "inicio", to:"plans#inicio"
  resources :plans do
    collection { post :import }
  end

  get "home/contribution", to: "home#contribution"
  root to: "home#index"
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  belongs_to :user
  has_many :objectives, dependent: :destroy
  validates :name, uniqueness: {
      scope: :user, message: "Você já possui esse Âmbito"
  }
  validates :name, presence: true
  validates :name, length: {minimum: 4, maximum: 30}
end

app/controllers/spheres_controller.rb
class SpheresController < ApplicationController
  load_and_authorize_resource
  before_action :set_sphere, only: [:edit, :update, :destroy]

  # GET /spheres
  # GET /spheres.json
  def index
    @spheres = current_user.spheres
  end

  # GET /spheres/new
  def new
    @sphere = Sphere.new
  end

  # GET /spheres/1/edit
  def edit
  end

  # POST /spheres
  # POST /spheres.json
  def create
    @sphere = Sphere.new(sphere_params)
    @sphere.user_id = current_user.id
    @sphere.progress = 0
    respond_to do |format|
      if @sphere.save
        format.html {redirect_to new_sphere_path, notice: "Âmbito foi criado com sucesso"}
      else
        format.html {render :new}
        format.json {render json: @sphere.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /spheres/1
  # PATCH/PUT /spheres/1.json
  def update
    respond_to do |format|
      if @sphere.update(sphere_params)
        format.html {redirect_to myplan_path, notice: "Âmbito foi atualizado com sucesso"}
      else
        format.html {render :edit}
        format.json {render json: @sphere.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /spheres/1
  # DELETE /spheres/1.json
  def destroy
    @sphere.destroy
    respond_to do |format|
      format.html {redirect_to myplan_path, notice: "Âmbito foi excluído com sucesso"}
      format.json {head :no_content}
    end
  end

  def sphereobjectives
    if Sphere.find(params[:sphere_id]).user_id == current_user.id
      @objectives = current_plan.objectives.where(sphere_id: params[:sphere_id]).where(plan_id: current_plan.id)
    else
      raise CanCan::AccessDenied.new('Você não pode acessar esse âmbito')
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sphere
    @sphere = Sphere.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sphere_params
    params.require(:sphere).permit(:name, :user_id, :progress)
  end

end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/views/spheres/_form.html.erb
<% @sphere.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<%= form_with(model: sphere, local: true) do |form| %>

  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label "Nome do âmbito" %>
        <%= form.text_field :name, autocomplete: "off",  class: "form-control" %>
      </div>
    </div>
  </div>

  <%= form.submit "Criar", class: "btn btn-primary" %>
<% end %>

app/views/spheres/_spheres.html.erb
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-t-10">
  <%= link_to sphereobjectives_path(sphere_id: spheres.id) do %>
    <div class="offer offer-radius offer-primary">
      <div class="shape">
        <div class="shape-text">
        </div>
      </div>
      <div class="offer-content">
        <h3 class="lead color-dark">
          <%= spheres.name %>
        </h3>
        <%= link_to " ",
                    edit_sphere_path(spheres),
                    class: "btn btn-default lnr lnr-pencil" %>
        <%= link_to " ",
                    spheres,
                    method: :delete,
                    data: {confirm: "Tem certeza que deseja remover o âmbito #{spheres.name}? Ao remover, tambem serão excluidos todos os objetivos estratégicos relacionados ao mesmo."},
                    class: "btn btn-danger lnr lnr-circle-minus" %>
      </div>
    </div>
  <% end %>
</div>

app/views/spheres/edit.html.erb
<div class="container">
  <h3>Editar Âmbito</h3>

  <%= render 'form', sphere: @sphere %>

  <%= link_to 'Back', spheres_path, class: "btn btn-default" %>
</div>

app/views/spheres/index.html.erb
<div class="container">
  <h3 class="p-t-50 p-b-20">Âmbitos</h3>
  <% if !@spheres.empty? %>
    <% @spheres.each do |sphere| %>
      <div class="col-sm-6">
        <div class="card" id="card_sphere">
          <div class="card-body">
            <h5 class="card-header">Âmbito</h5>
            <div class="padding-all">
              <h5 class="card-title"><%= sphere.name %></h5>
              <%= link_to " ",
                          edit_sphere_path(sphere),
                          class: "btn btn-default lnr lnr-pencil",
                          id: "button-edit-sphere"
              %>
              <%= link_to " ",
                          sphere,
                          method: :delete,
                          data: {confirm: "Tem certeza que deseja remover o âmbito #{sphere.name}? Ao remover, tambem serão excluidos todos os objetivos estratégicos relacionados ao mesmo."},
                          class: "btn btn-danger lnr lnr-circle-minus",
                          id: "button-delete-sphere"
              %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <h3>Você ainda não criou um âmbito.</h3>
    <br/>
  <% end %>
  <%= link_to "Novo Âmbito", new_sphere_path, class: "btn btn-primary" %>

</div>

app/views/spheres/new.html.erb
<div class="container">

  <div class="wrap-collabsible p-t-60 p-b-20">
    <input id="collapsible" class="toggle" type="checkbox" style="display: none" checked>
    <label for="collapsible" class="lbl-toggle">ÂMBITOS</label>
    <div class="collapsible-content">
      <div class="content-inner">
        <div class="content-text p-b-10">
          Os Âmbitos representam os círculos que irão envolver seus objetivos.
          <br/>
          <br/>
          Exemplos de Âmbitos:
          <br/>
          <br/>
          Profissional<br/>
          Familiar<br/>
          Financeiro<br/>
        </div>
      </div>
    </div>
  </div>

  <h3>Meus Âmbitos</h3>
  <% if !current_user.spheres.nil? %>
    <div class="row">
      <%= render partial: "spheres/spheres", collection: current_user.spheres %>
    </div>
  <% end %>
  <br/>
  <%= render 'form', sphere: @sphere %>

  <br/>
  <div class="justify-buttons">
    <%= link_to " Voltar para Fatores Críticos de Sucesso", new_csf_path, class: "btn btn-default lnr lnr-arrow-left" %>
    <%= link_to " Continuar para Objetivos Estratégicos", new_objective_path, class: "btn btn-primary lnr lnr-arrow-right align-right" %>
  </div>
</div>

app/views/spheres/sphereobjectives.html.erb
<div class="container">
  <div class="col-xs-12  p-t-10">
    <h3>Objetivos do Âmbito</h3>
    <% if !@objectives.empty? %>
      <% @objectives.each_with_index do |objective, i| %>
        <%= link_to editobjective_path(objective_id: objective.id) do %>
          <div class="offer offer-radius offer-info">
            <div class="shape">
              <div class="shape-text">
                <%= i + 1 %>
              </div>
            </div>
            <div class="offer-content">
              <h3 class="lead color-dark">
                <%= objective.name %><br/>
                Criado em: <%= objective.created_at.strftime("%d/%m/%Y") %>
              </h3>
              <p>
                <%= render partial: "goals/goal", :collection => objective.goals %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h3>Você ainda não tem objetivos nesse âmbito.</h3>
      <br/>
      <%= link_to "Criar Objetivo", new_objective_path, class:"btn btn-primary" %>
    <% end %>
  </div>
</div>