config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :roles
  put "csfs/update_selected_csf", to: "csfs#update_selected_csf"
  resources :csfs
  resources :values
  put "visions/update_selected_vision", to: "visions#update_selected_vision"
  resources :visions, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :activities do
    collection do
      put :checked
    end
  end
  resources :goals

  get "spheres/update_sphere_completion", to: "spheres#update_sphere_completion"
  get "sphereobjectives", to: "spheres#sphereobjectives"
  resources :spheres

  get "editobjective", to: "objectives#editobjective"
  resources :objectives

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
    delete 'users/destroy_another_user', :to => 'users/registrations#destroy_another_user'
  end
  resources :swotparts

  put "missions/update_selected_mission", to: "missions#update_selected_mission"
  resources :missions, only: [:index, :new, :create, :destroy, :edit, :update]

  get "plans/import_page", to: "plans#import_page"
  get "plans/export", to: "plans#export"
  get "plans/pdf", to: "plans#pdf"
  put "plans/update_selected_plan", to: "plans#update_selected_plan"
  get "swot", to:"plans#swot"
  get "myplan", to: "plans#myplan"
  get "plans/swotedit", to: "plans#swotedit"
  get "inicio", to:"plans#inicio"
  resources :plans do
    collection { post :import }
  end

  get "home/contribution", to: "home#contribution"
  root to: "home#index"
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :objective
  has_many :activities, dependent: :destroy
  validates :name, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
    authorize! :index, @goals
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
    @objective_id = params[:objective_id]

  end

  # GET /goals/1/edit
  def edit
    @objective_id = params[:objective_id]
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.progress = 0

    respond_to do |format|
      if @goal.save
        format.html { redirect_to editobjective_path(objective_id: @goal.objective_id), notice: "Meta criada com sucesso" }
        format.json { render :show, status: :created, location: @goal }
      else
        @objective_id = params[:goal][:objective_id]
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to editobjective_path(objective_id: @goal.objective_id), notice: "Meta atualizada com sucesso" }
        format.json { render :show, status: :ok, location: @goal }
      else
        @objective_id = params[:goal][:objective_id]
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to editobjective_path(objective_id: @goal.objective_id), notice: "Meta excluída com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name, :progress, :objective_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_cardgoal.erb
<div class="row">
  <div class="col-border">
    <div class="card">
      <div class="card-body">
        <div class="padding-all">
          <div class="goal-description">
            <div class="goal-activities">
              <h4 class="card-title">Nome da meta: <%= cardgoal.name %>
                <%= link_to " ", edit_goal_path(cardgoal, :objective_id => cardgoal.objective), id:"button-edit-goal", class: "lnr lnr-pencil" %>
                <%= link_to " ", cardgoal, method: :delete, data: {confirm: 'Tem certeza que quer remover essa meta?'}, id:"button-delete-goal", class: "lnr lnr-circle-minus" %>
              </h4>
              <span class="card-divider"></span>
              <br/>
              <h5 class="card-title">
                Atividades
                <%= link_to " ", new_activity_path(goal_id: cardgoal.id), id:"button-create-activity",class: "lnr lnr-plus-circle btn btn-primary" %>
              </h5>
              <%= form_tag checked_activities_path(goal_id: cardgoal.id), method: :put do %>
                <table>
                  <tbody>
                  <% cardgoal.activities.each do |activity| %>
                    <tr>
                      <td><%= check_box_tag "activity_ids[]", activity.id, activity.checked %></td>
                      <td><%= activity.title %></td>
                      <td><%= link_to " ", activity, method: :delete, id:"button-delete-activity", class:"lnr lnr-circle-minus" %></td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
                <br/>
                <%= submit_tag "Atualizar progresso", id:"button-update-goal-progress", class:"btn btn-success" %>
              <% end %>
            </div>
            <div class="goal-progress">
              <h5 class="card-title"><%= cardgoal.name %> </h5>
              <% goal_data = [["", cardgoal.progress]] %>
              <%= bar_chart goal_data, suffix: "%", label: "Porcentagem concluída", min: 0, max: 100, height: "70px", width: "100%" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/_form.html.erb
<% @goal.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<%= form_with(model: goal, local: true) do |form| %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label "Nome da meta" %>
        <%= form.text_field :name, autocomplete: "off",  class: "form-control", id: "field-goal-name" %>
      </div>
    </div>
  </div>

  <%= form.hidden_field :objective_id, value: @objective_id %>

  <%= form.submit "Salvar", class: "btn btn-primary" %>

<% end %>

app/views/goals/_goal.html.erb
<div class="row">
  <div class="col-border">
    <div class="card">
      <div class="card-body">
        <div class="padding-all">
          <h5 class="card-title"><%= goal.name %> </h5>
          <% goal_data = [["", goal.progress ]] %>
          <%= bar_chart goal_data, suffix: "%", label: "Porcentagem concluída",  min: 0, max: 100, height: "70px" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<div class="container">
  <h3>Edição de meta</h3>

  <%= render 'form', goal: @goal %>
  <br/>
</div>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Progress</th>
      <th>Objective</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= render @goals %>
  </tbody>
</table>

app/views/goals/new.html.erb
<div class="container">
  <div class="wrap-collabsible p-t-60 p-b-20">
    <input id="collapsible" class="toggle" type="checkbox" style="display: none" checked>
    <label for="collapsible" class="lbl-toggle">METAS</label>
    <div class="collapsible-content">
      <div class="content-inner">
        <div class="content-text p-b-10">
          Metas ajudam a dividir um objetivo em partes menores.
          A partir de cada meta, a seguir você deve elaborar atividades
          para a conclusão da mesma.
          <br/>
          <br/>
          Exemplos de Metas para o Objetivo Estratégico Aprender uma nova lingua:
          <br/>
          <br/>
          Escolher uma lingua para aprender<br/>
          Fazer curso<br/>
          Me tornar fluente<br/>
        </div>
      </div>
    </div>
  </div>

  <h3>Nova Meta</h3>
  <br/>

  <%= render 'form', goal: @goal %>
  <br/>
</div>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @goal.progress %>
</p>

<p>
  <strong>Objective:</strong>
  <%= @goal.objective %>
</p>

<%= link_to 'Back', goals_path %>