config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index, :show, :new, :create, :destroy]

  resources :roles
  put "csfs/update_selected_csf", to: "csfs#update_selected_csf"
  resources :csfs
  resources :values
  put "visions/update_selected_vision", to: "visions#update_selected_vision"
  resources :visions, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :activities do
    collection do
      put :checked
    end
  end
  resources :goals

  get "spheres/update_sphere_completion", to: "spheres#update_sphere_completion"
  get "sphereobjectives", to: "spheres#sphereobjectives"
  resources :spheres

  get "editobjective", to: "objectives#editobjective"
  resources :objectives

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  devise_scope :user do
    get 'users', :to => 'users/registrations#index'
    delete 'users/destroy_another_user', :to => 'users/registrations#destroy_another_user'
  end
  resources :swotparts

  put "missions/update_selected_mission", to: "missions#update_selected_mission"
  resources :missions, only: [:index, :new, :create, :destroy, :edit, :update]

  get "plans/import_page", to: "plans#import_page"
  get "plans/export", to: "plans#export"
  get "plans/pdf", to: "plans#pdf"
  put "plans/update_selected_plan", to: "plans#update_selected_plan"
  get "swot", to:"plans#swot"
  get "myplan", to: "plans#myplan"
  get "plans/swotedit", to: "plans#swotedit"
  get "inicio", to:"plans#inicio"
  resources :plans do
    collection { post :import }
  end

  get "home/contribution", to: "home#contribution"
  root to: "home#index"
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :swotparts, dependent: :destroy
  has_many :objectives, dependent: :destroy
  has_many :values, dependent: :destroy
  has_many :roles, dependent: :destroy

  validates :name, presence: true
  validates :name, length: {minimum: 4, maximum: 30}
end

app/controllers/plans_controller.rb
require 'json'
require 'uri'

class PlansController < ApplicationController
  load_and_authorize_resource
  before_action :set_plan, only: [:edit, :update, :destroy]


  # GET /plans
  # GET /plans.json
  def index
    @plans = current_user.plans
  end

  def myplan
    if current_plan
      @my_mission = Mission.find(current_plan.selected_mission) rescue nil
      @my_vision = Vision.find(current_plan.selected_vision) rescue nil
      @my_csf = Csf.find(current_plan.selected_csf) rescue nil
      @strengths = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :strength)
      @weaks = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :weak)
      @opportunities = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :opportunity)
      @threats = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :threat)
      @objectives = current_plan.objectives
      @spheres = current_user.spheres
      @value = Value.new
      @role = Role.new
    else
      redirect_to plans_path
    end
  end

  def import_page
  end

  def import
    begin
      import_plan(params[:file])
    rescue StandardError => bang
      flash[:info] = "Erro na importação de planos: #{bang}"
      redirect_to plans_import_page_path
    end
  end

  def export
    if current_plan
      @user = current_user
      @spheres = current_user.spheres
      @plans = current_user.plans
      @objectives = current_plan.objectives
      @missions = current_user.missions
      @visions = current_user.visions
      @csfs = current_user.csfs
      @swotparts = current_plan.swotparts
      @values = current_plan.values
      @roles = current_plan.roles

      respond_to do |format|
        format.json do
          data = render_to_string(template: "plans/export.json.jbuilder", formats: 'json')
          send_data data, type: 'application/json; header=present', disposition: "attachment; filename=#{current_user.email}_plans.json"
        end
      end
    else
      redirect_to plans_path
    end
  end

  def pdf
    if current_plan
      @my_mission = Mission.find(current_plan.selected_mission) rescue nil
      @my_vision = Vision.find(current_plan.selected_vision) rescue nil
      @my_csf = Csf.find(current_plan.selected_csf) rescue nil
      @strengths = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :strength)
      @weaks = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :weak)
      @opportunities = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :opportunity)
      @threats = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :threat)
      @objectives = current_plan.objectives
      @spheres = current_user.spheres
      @value = Value.new
      @role = Role.new

      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Planejamento de #{current_user.name}",
                 page_size: "A4",
                 template: "plans/pdf.html.erb",
                 orientation: "Portrait",
                 title: "Planejamento de #{current_user.name}",
                 plans: "pdf.html.erb",
                 lowquality: true,
                 grayscale: true,
                 zoom: 1,
                 dpi: 75,
                 margin: {top: 10,
                          bottom: 10,
                          left: 10,
                          right: 10},
                 disable_links: true,
                 disable_toc_links: true,
                 disable_back_links: true,
                 javascript_delay: 3000
        end
      end
    else
      redirect_to plans_path
    end
  end

  def swotedit
    if current_plan
      @strengths = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :strength)
      @weaks = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :weak)
      @opportunities = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :opportunity)
      @threats = current_plan.swotparts.where(plan_id: current_plan.id).where(partname: :threat)
    else
      redirect_to plans_path
    end
  end

  def inicio
    if current_plan
      @strengths = Swotpart.where(plan_id: current_plan.id).where(partname: :strength)
      @weaks = Swotpart.where(plan_id: current_plan.id).where(partname: :weak)
      @opportunities = Swotpart.where(plan_id: current_plan.id).where(partname: :opportunity)
      @threats = Swotpart.where(plan_id: current_plan.id).where(partname: :threat)

      @objectives = current_plan.objectives
      @spheres = current_user.spheres


      @chartColors = [
          ['rgba(255, 0, 0, 0.71)'],
          ['rgba(255, 255, 0, 0.71)'],
          ['rgba(0, 168, 0, 0.71)']
      ]
    else
      redirect_to plans_path
    end

  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id

    respond_to do |format|
      if @plan.save
        current_user.update_attribute(:selected_plan, @plan.id)
        format.html {redirect_to plans_swotedit_path, notice: "Plano criado com sucesso"}
      else
        format.html {render :new}
        format.json {render json: @plan.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html {redirect_to plans_path, notice: "Plano atualizado com sucesso"}
      else
        format.html {render :edit}
        format.json {render json: @plan.errors, status: :unprocessable_entity}
      end
    end
  end

  def update_selected_plan
    current_user.update_attribute(:selected_plan, params[:plan_id])
    flash[:notice] = "Plano selecionada foi atualizada com sucesso"
    redirect_to myplan_path
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    current_user.selected_plan = nil
    current_user.save
    @plan.destroy
    respond_to do |format|
      flash[:info] = "Plano foi excluído"
      format.html {redirect_to plans_url}
      format.json {head :no_content}
    end
  end

  private

  def create_sphere(hash_sphere)
    new_sphere = Sphere.new
    new_sphere.user_id = current_user.id
    new_sphere.name = hash_sphere[:name]
    new_sphere.progress = hash_sphere[:progress]
    # Spheres validates name duplications
    new_sphere.save ? new_sphere : current_user.spheres.where(name: "#{hash_sphere[:name]}").first
  end

  def create_plan(hash_plan, user_id)
    new_plan = Plan.new
    new_plan.user_id = user_id
    new_plan.name = hash_plan[:name]
    new_plan.selected_mission = hash_plan[:selected_mission]
    new_plan.selected_vision = hash_plan[:selected_vision]
    new_plan.selected_csf = hash_plan[:selected_csf]
    new_plan.save ? new_plan.id : nil
  end

  def create_swotpart(hash_swotpart, plan_id)
    new_swotpart = Swotpart.new
    new_swotpart.plan_id = plan_id
    new_swotpart.name = hash_swotpart[:name]
    new_swotpart.partname = hash_swotpart[:partname]
    new_swotpart.save
  end

  def create_value(hash_value, plan_id)
    new_value = Value.new
    new_value.plan_id = plan_id
    new_value.name = hash_value[:name]
    new_value.save
  end

  def create_role(hash_role, plan_id)
    new_role = Role.new
    new_role.plan_id = plan_id
    new_role.name = hash_role[:name]
    new_role.description = hash_role[:description]
    new_role.name = hash_role[:name]
    new_role.save
  end

  def create_objective(hash_objective, plan_id, sphere_id)
    new_objective = Objective.new
    new_objective.plan_id = plan_id
    new_objective.sphere_id = sphere_id
    new_objective.name = hash_objective[:name]
    new_objective.concluded = hash_objective[:concluded]
    new_objective.save ? new_objective.id : nil
  end

  def create_goal(hash_goal, objective_id)
    new_goal = Goal.new
    new_goal.objective_id = objective_id
    new_goal.name = hash_goal[:name]
    new_goal.progress = hash_goal[:progress]
    new_goal.save ? new_goal.id : nil
  end

  def create_activity(hash_activity, goal_id)
    new_activity = Activity.new
    new_activity.goal_id = goal_id
    new_activity.title = hash_activity[:title]
    new_activity.checked = hash_activity[:checked]
    new_activity.save
  end

  def create_mission(hash_mission, user_id)
    new_mission = Mission.new
    new_mission.user_id = user_id
    new_mission.purpose_of_life = hash_mission[:purpose_of_life]
    new_mission.who_am_i = hash_mission[:who_am_i]
    new_mission.why_exist = hash_mission[:why_exist]
    new_mission.save
  end

  def create_vision(hash_vision, user_id)
    new_vision = Vision.new
    new_vision.user_id = user_id
    new_vision.where_im_going = hash_vision[:where_im_going]
    new_vision.where_arrive = hash_vision[:where_arrive]
    new_vision.how_complete_mission = hash_vision[:how_complete_mission]
    new_vision.save
  end

  def create_csf(hash_csf, user_id)
    new_csf = Csf.new
    new_csf.user_id = user_id
    new_csf.what_makes_me_unique = hash_csf[:what_makes_me_unique]
    new_csf.best_attributes = hash_csf[:best_attributes]
    new_csf.essential_atributes = hash_csf[:essential_atributes]
    new_csf.health_factors = hash_csf[:health_factors]
    new_csf.save
  end

  def import_plan(file)
    puts "---- Inicio da importação------"
    puts file.path
    puts file.size
    puts file.content_type

    # 20000 bytes = 20 kilobyte = 0.02 Megabytes
    if file.size > 20000
      raise StandardError.new('Erro de tamanho de arquivo')
    end

    file_string = file.path.to_s

    if (file_string[-5, 5]).eql? '.json'
      IO.foreach(Rails.root.join(file.path)) do |plan_json_line|
        begin
          plans_hash = JSON.parse(plan_json_line)
          create_all_plans(plans_hash)
        rescue JSON::ParserError, TypeError => e

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_inputswotpart.html.erb
<%= form_tag swotparts_path do %>
  <%= hidden_field_tag :partname, tipo_do_swotpart %>

  <div class="field-group-swot m-t-20">
    <%= text_field_tag :name,
                       nil,
                       autocomplete: "off",
                       placeholder: "Adicionar #{texto_da_acao}",
                       class: "field-add-swot",
                       id: "field-#{texto_da_acao}"
    %>
    <%= button_tag class: "icon-add-swot", id: "add-#{texto_da_acao}" do %>
      <i class="lnr lnr-arrow-right"> Adicionar </i>
    <% end %>
  </div>
<% end %>

app/views/plans/import_page.html.erb
<div class="container">
  <div class="wrap-collabsible p-t-60 p-b-20">
    <input id="collapsible" class="toggle" type="checkbox" style="display: none" checked>
    <label for="collapsible" class="lbl-toggle">Importar Planos</label>
    <div class="collapsible-content">
      <div class="content-inner">
        <div class="content-text p-b-10">
          Faça upload dos seus planos a partir de um arquivo gerado no Life to Remind previamente. Clique em Procurar arquivo para importar.

          <br/>
          <br/>
          Para importar dados com sucesso, seu arquivo deve:

          <br/>
          <br/>
          - Deve conter um JSON valido.
          <br/>
          - Deve ter no máximo 20 kbytes.
          <br/>
          - Não deve ter sido alterado pelo usuário.
          <br/>
          <br/>

        </div>
      </div>
    </div>
  </div>
  <!--
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
  </div>
  -->

  <%= form_tag import_plans_path, multipart: true  do %>
    <%= file_field_tag :file, class: "custom-file-input", accept: "application/json" %>
    <br/>
    <div class="align-right">
      <%= link_to " Gerenciar Planos", plans_path, class: "btn btn-default lnr lnr-cog" %>
    </div>
    <%= submit_tag "Importar", class: "btn btn-primary", id: "file-plans-submit", data: { disable_with: "Enviando arquivo..." } %>
  <% end %>
</div>

app/views/plans/index.html.erb
<div class="container">
  <div class="row">
    <% if @plans.empty? %>
      <%= render "plans/welcome" %>
    <% else %>
      <% if current_user.selected_plan.nil? %>
        <div class="body-tutorial">
          <figure class="card-tutorial card-tutorial--water">
            <figcaption class="card-tutorial__caption">
              <h3 class="card-tutorial__type h3-tutorial card__type">
                PLANOS
              </h3>
              <h4 class="card-tutorial__abilities h4-tutorial p-t-10 p-b-10">
                Selecione um plano
              </h4>

            </figcaption>
          </figure>
        </div>
      <% end %>
    <% end %>

    <% @plans.each_with_index do |plan, i| %>

      <% if (i % 2 == 0) %>
        <div class="blog-card" id="card_plan">
          <div class="meta">
            <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg)"></div>
            <ul class="details">
              <li class="author"><a href="#"><%= current_user.name %></a></li>
              <li class="date"><%= plan.created_at.strftime("%d de %B de %Y") %>></li>
              <!--<li class="tags">
                <ul>
                  <li><a href="#">Learn</a></li>
                  <li><a href="#">Code</a></li>
                  <li><a href="#">HTML</a></li>
                  <li><a href="#">CSS</a></li>
                </ul>
              </li>-->
            </ul>
          </div>
          <div class="description">
            <h1><%= plan.name %></h1>
            <p>Plano <%= i + 1 %></p>
            <p>
              <%= link_to "Selecionar",
                          plans_update_selected_plan_path(plan_id: plan.id), method: :put,
                          class: "btn btn-primary",
                          id: "button-select-plan" %>
              <%= link_to "",
                          edit_plan_path(plan),
                          class: "lnr lnr-pencil btn btn-default",
                          id: "button-edit-plan" %>
              <%= link_to "",
                          plan,
                          method: :delete,
                          class: "lnr lnr-circle-minus btn btn-danger",
                          data: {confirm: "Tem certeza que deseja remover o plano #{plan.name}?"},
                          id: "button-delete-plan" %>
            </p>
          </div>
        </div>
      <% else %>
        <div class="blog-card alt" id="card_plan">
          <div class="meta">
            <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-2.jpg)"></div>
            <ul class="details">
              <li class="author"><a href="#"><%= current_user.name %></a></li>
              <li class="date"><%= plan.created_at.strftime("%d de %B de %Y") %>></li>
            </ul>
          </div>
          <div class="description">
            <h1><%= plan.name %></h1>
            <p>Plano <%= i + 1 %></p>
            <p>
              <%= link_to "Selecionar",
                          plans_update_selected_plan_path(plan_id: plan.id), method: :put,
                          class: "btn btn-primary",
                          id: "button-select-plan" %>
              <%= link_to "",
                          edit_plan_path(plan),
                          class: "lnr lnr-pencil btn btn-default",
                          id: "button-edit-plan" %>
              <%= link_to "",
                          plan,
                          method: :delete,
                          class: "lnr lnr-circle-minus btn btn-danger",
                          data: {confirm: "Tem certeza que deseja remover o plano #{plan.name}?"},
                          id: "button-delete-plan" %>
            </p>
          </div>
        </div>
      <% end %>

    <% end %>
  </div>
  <br>
  <span class="align-right">
    <%= link_to " Carregar Planos", plans_import_page_path, class: "btn btn-success btn-outline lnr lnr-upload", id:"load-plans" %>
    <%= link_to " Exportar Planos", plans_export_path(format: "json"), data: {disable_with: " Arquivo Gerado"}, class: "btn btn-dark btn-outline lnr lnr-download", id: "export-plans" %>
    <br/>
    * Ao exportar planos pode ser perguntado se o
    <br/>
    usuário deseja manter o arquivo.
  </span>
  <%= link_to "Novo plano", new_plan_path, class: "btn btn-primary", id: "button-create-plan" %>
</div>

app/views/plans/myplan.html.erb
<div class="container p-t-40">
  <% if current_user.selected_plan %>
    <div class="p-b-10" align="right">
      <%= link_to " Gerar PDF", plans_pdf_path(id: @current_plan, format: :pdf), data: {disable_with: " Gerando arquivo..."}, class: "btn btn-warning lnr lnr-file-add" %>
      <%= link_to " Passo a passo", plans_swotedit_path, class: "btn btn-success lnr lnr-list" %>
      <%= link_to " Gerenciar Planos", plans_path, method: "get", class: "btn btn-primary lnr lnr-cog" %>
    </div>
    <div class="row">
      <div class="card-plan">
        <div class="card-body">
          <h5 class="p-b-20 text-align-center">
            <div class="col-md-12 p-t-20 p-b-20">
              <h4 class="color-ltr-myplan"><span><%= current_user.name %></span></h4>
              <h4 class="text-ltr">Planejamento Estratégico Pessoal</h4>
              <h4 class="text-ltr">Nome do Plano: <%= "#{@current_plan.name}" %></h4>
              <h4 class="text-ltr"><%= @current_plan.created_at.strftime("%d/%m/%Y") %></h4>
            </div>
          </h5>
          <div class="padding-all">

            <!-- SWOT Matrix -->
            <h3>Matriz
              SWOT <%= link_to "", plans_swotedit_path, method: "get", class: "btn btn-success lnr lnr-pencil align-right" %></h3>
            <br/>
            <p class="card-text"><%= render template: "plans/swot" %></p>
            <hr/>

            <div class="row">
              <div class="padding-all">
                <!-- Mission -->
                <% if @my_mission %>
                  <%= link_to missions_path, id: "button-missions" do %>
                    <div class="col-xs-5  p-t-10">
                      <div class="offer offer-radius offer-warning">
                        <div class="shape">
                          <div class="shape-text">
                          </div>
                        </div>
                        <div class="offer-content">
                          <h3 class="color-dark">Minha Missão </h3>
                          <hr/>
                          <h3 class="lead color-dark m-b-5">Propósito de Vida</h3>
                          <p><%= "#{@my_mission.purpose_of_life}" %></p>
                          <h3 class="lead color-dark m-b-5">Quem sou eu</h3>
                          <p><%= "#{@my_mission.who_am_i}" %></p>
                          <h3 class="lead color-dark m-b-5">Porque existo</h3>
                          <p><%= "#{@my_mission.why_exist}" %></p>
                          <p>
                            Criado em: <%= @my_mission.created_at.strftime("%d/%m/%Y") %>
                          </p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to missions_path, id: "button-missions-cog" do %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-t-10">
                      <div class="dashed dashed-border">
                        <div class="dashed-content ">
                          <h3 class="lead box-gray-dashed">
                            <span class="lnr lnr-cog"> Missão</span>
                            <h6 class="color-gray" align="center" id="myplan-user-missions">Missões disponíveis de <%= current_user.name %>: <%= current_user.missions.count %></h6>
                          </h3>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>

                <!-- Vision -->
                <% if @my_vision %>
                  <%= link_to visions_path, id: "button-visions" do %>
                    <div class="col-xs-7  p-t-10">
                      <div class="offer offer-radius offer-danger">
                        <div class="shape">
                          <div class="shape-text">
                          </div>
                        </div>
                        <div class="offer-content">
                          <h3 class="color-dark">Minha Visão </h3>
                          <hr/>
                          <h3 class="lead color-dark m-b-5">Para onde vou?</h3>
                          <p><%= "#{@my_vision.where_im_going}" %></p>
                          <h3 class="lead color-dark m-b-5">Onde quero chegar?</h3>
                          <p><%= "#{@my_vision.where_arrive}" %></p>
                          <h3 class="lead color-dark m-b-5">Como tornarei concreta a minha missão?</h3>
                          <p><%= "#{@my_vision.how_complete_mission}" %></p>
                          <p>
                            Criado em: <%= @my_vision.created_at.strftime("%d/%m/%Y") %>
                          </p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to visions_path, id: "button-visions-cog" do %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-t-10">
                      <div class="dashed dashed-border">
                        <div class="dashed-content ">
                          <h3 class="lead box-gray-dashed">
                            <span class="lnr lnr-cog"> Visão</span>
                            <h6 class="color-gray" align="center" id="myplan-user-visions">Visões disponíveis de <%= current_user.name %>: <%= current_user.visions.count %></h6>
                          </h3>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <hr/>

            <!-- Values -->
            <div class="row">
              <div class="padding-all">
                <h3>Meus Valores</h3>
                <div class="row">
                  <%= render partial: "values/values", collection: @current_plan.values %>
                </div>
                <div class="row p-l-20">
                  <%= render partial: "values/form" %>
                </div>
              </div>
            </div>
            <hr/>

            <!-- Roles -->
            <div class="row">
              <div class="padding-all">
                <h3>Meus Papéis</h3>
                <div class="row p-t-20">
                  <table>
                    <tbody>
                    <td width="100px" class="p-l-30">Papel chave</td>
                    <td width="300px" class="p-l-60">Como me vejo no futuro</td>
                    </tbody>
                  </table>
                  <%= render partial: "roles/roles", collection: @current_plan.roles %>
                </div>
                <div class="row">
                  <%= render partial: "roles/form" %>
                </div>
              </div>
            </div>
            <hr/>

            <!-- Critical Success Factors -->
            <div class="row">
              <div class="padding-all">
                <% if @my_csf %>
                  <%= link_to csfs_path, id: "button-csfs" do %>
                    <div class="col-xs-12 p-t-10">
                      <div class="offer offer-radius offer-default">
                        <div class="shape">
                          <div class="shape-text">
                          </div>
                        </div>
                        <div class="offer-content">
                          <h3 class="color-dark">Meus Fatores Críticos de Sucesso </h3>
                          <hr/>
                          <h3 class="lead color-dark m-b-5">Que características me tornam único?</h3>
                          <p><%= "#{@my_csf.what_makes_me_unique}" %></p>
                          <h3 class="lead color-dark m-b-5">Quais minhas melhores competências?</h3>
                          <p><%= "#{@my_csf.best_attributes}" %></p>
                          <h3 class="lead color-dark m-b-5">Quais delas são essenciais para meus objetivos?</h3>
                          <p><%= "#{@my_csf.essential_atributes}" %></p>
                          <h3 class="lead color-dark m-b-5">Quais fatores impactam no meu bem estar?</h3>
                          <p><%= "#{@my_csf.health_factors}" %></p>
                          <p class="p-l-15 p-b-5 p-r-5 align-right"><%= @my_csf.created_at.strftime("%d/%m/%Y") %></p>

                        </div>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to csfs_path, id: "button-csfs-cog" do %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-t-10">
                      <div class="dashed dashed-border">
                        <div class="dashed-content ">
                          <h3 class="lead box-gray-dashed">
                            <span class="lnr lnr-cog"> Fator Crítico de Sucesso</span>
                            <h6 class="color-gray" align="center" id="myplan-user-csfs">Fatores críticos de sucesso disponíveis de <%= current_user.name %>: <%= current_user.csfs.count %></h6>
                          </h3>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <hr/>

            <!-- Spheres -->
            <h3>Âmbitos</h3>
            <% if !current_user.spheres.nil? %>
              <div class="row">
                <%= render partial: "spheres/spheres", collection: @spheres %>
                <%= link_to new_sphere_path do %>
                  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 p-t-10">
                    <div class="dashed dashed-border">
                      <div class="dashed-content ">
                        <h3 class="lead box-gray-dashed">
                          <span class="lnr lnr-plus-circle"></span>
                        </h3>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              Crie um âmbito de vida para seus objetivos
              <%= link_to " Criar", new_sphere_path, class: "btn btn-primary lnr lnr-plus-circle" %></h3>
            <% end %>
            <hr/>

            <!-- Strategic Objectives -->
            <h3>Objetivos Estratégicos</h3>
            <% if !@current_plan.objectives.nil? %>
              <div class="row">
                <%= render template: "objectives/index" %>
              </div>
              <div class="row">
                <%= link_to new_objective_path, id: "button-create-objective" do %>
                  <div class="col-xs-12 p-t-10">
                    <div class="dashed dashed-border">
                      <div class="dashed-content">
                        <h3 class="lead box-gray-dashed">
                          <span class="lnr lnr-plus-circle"></span>
                        </h3>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              Crie seu primeiro Objetivo Estratégico Pessoal
              <%= link_to " Criar", new_objective_path, class: "btn btn-primary lnr lnr-plus-circle" %></h3>
            <% end %>
            <hr/>

          </div>
        </div>
      </div>
    </div>
  <% else %>
    <p>Parece que você ainda não criou um planejamento.</p>
    <%= link_to "Crie um novo plano", new_plan_path, method: "get", class: "btn btn-primary" %>
  <% end %>
</div>